Output "/Users/kaypark/workspace/colorscheme/emacs-nepes/docs/light.gif"
Set Width 1280
Set Height 720
Set FontSize 14

Type "emacs -nw -Q -l nepes-light-theme.el --eval '(load-theme (quote nepes-light) t)' /Users/kaypark/workspace/colorscheme/nepes-palette/captures/samples/showcase.py"
Enter
Sleep 4s
Screenshot "/Users/kaypark/workspace/colorscheme/emacs-nepes/docs/light.png"
Sleep 1s
Ctrl+x
Ctrl+c
